# -*- coding: utf-8 -*-
"""capture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VZfgv068tnGXUb1rqVGANEP8sVlfVJcn
"""

# ! pip install face_recognition

"""# ライブラリのインポート"""

import sys
import face_recognition
import cv2
import numpy as np
from PIL import ImageFont, ImageDraw, Image
import glob # ファイル操作ができるライブラリ

# 顔の位置情報を格納する変数
face_locations = []


video_capture = cv2.VideoCapture(0)

def main():
  while True:
    # ビデオの単一フレームを取得
    _, frame = video_capture.read()

    # 顔の位置情報を検索
    face_locations = face_recognition.face_locations(frame)

    # 顔の位置情報を表示させる
    for (top, right, bottom, left) in face_locations:
      # 顔領域に枠を付けていく
      cv2.rectangle(frame, (left, top), (right, bottom) , (0,0,255), 2)

    # 結果をビデオに表示
    cv2.imshow('Video', frame)

    # ESCキーで終了
    if cv2.waitKey(1) == 27:
      break

main()

video_capture.release()
cv2.destoryAllWindows()